/**
 * Standardized error codes for the MyloWare platform
 */
export const ERROR_CODES = {
  // General errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',

  // Database errors
  DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
  DATABASE_QUERY_ERROR: 'DATABASE_QUERY_ERROR',
  DATABASE_CONSTRAINT_ERROR: 'DATABASE_CONSTRAINT_ERROR',

  // Redis errors
  REDIS_CONNECTION_ERROR: 'REDIS_CONNECTION_ERROR',
  REDIS_OPERATION_ERROR: 'REDIS_OPERATION_ERROR',

  // Temporal errors
  TEMPORAL_CONNECTION_ERROR: 'TEMPORAL_CONNECTION_ERROR',
  WORKFLOW_EXECUTION_ERROR: 'WORKFLOW_EXECUTION_ERROR',

  // Agent errors
  AGENT_INITIALIZATION_ERROR: 'AGENT_INITIALIZATION_ERROR',
  AGENT_EXECUTION_ERROR: 'AGENT_EXECUTION_ERROR',
  TOOL_EXECUTION_ERROR: 'TOOL_EXECUTION_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
