/**
 * Standardized error codes for the MyloWare platform
 */
export declare const ERROR_CODES: {
  readonly INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR';
  readonly VALIDATION_ERROR: 'VALIDATION_ERROR';
  readonly NOT_FOUND: 'NOT_FOUND';
  readonly UNAUTHORIZED: 'UNAUTHORIZED';
  readonly FORBIDDEN: 'FORBIDDEN';
  readonly CONFLICT: 'CONFLICT';
  readonly DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR';
  readonly DATABASE_QUERY_ERROR: 'DATABASE_QUERY_ERROR';
  readonly DATABASE_CONSTRAINT_ERROR: 'DATABASE_CONSTRAINT_ERROR';
  readonly REDIS_CONNECTION_ERROR: 'REDIS_CONNECTION_ERROR';
  readonly REDIS_OPERATION_ERROR: 'REDIS_OPERATION_ERROR';
  readonly TEMPORAL_CONNECTION_ERROR: 'TEMPORAL_CONNECTION_ERROR';
  readonly WORKFLOW_EXECUTION_ERROR: 'WORKFLOW_EXECUTION_ERROR';
  readonly AGENT_INITIALIZATION_ERROR: 'AGENT_INITIALIZATION_ERROR';
  readonly AGENT_EXECUTION_ERROR: 'AGENT_EXECUTION_ERROR';
  readonly TOOL_EXECUTION_ERROR: 'TOOL_EXECUTION_ERROR';
};
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
//# sourceMappingURL=error-codes.d.ts.map
