#!/usr/bin/env tsx
/**
 * Auto-generate reference documentation from source code
 * 
 * Usage:
 *   npm run docs:generate
 *   npm run docs:generate -- --tools
 *   npm run docs:generate -- --schema
 */

import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const DOCS_DIR = join(__dirname, '../../docs/06-reference');

// Parse CLI args
const args = process.argv.slice(2);
const generateTools = args.length === 0 || args.includes('--tools');
const generateSchema = args.length === 0 || args.includes('--schema');

/**
 * Generate MCP tools documentation from src/mcp/tools.ts
 */
function generateToolsDocs() {
  console.log('Generating MCP tools documentation...');
  
  const content = `# MCP Tools Reference

**Auto-generated from \`src/mcp/tools.ts\`**  
**Last updated:** ${new Date().toISOString().split('T')[0]}

> ⚠️ **Do not edit this file manually.** It is auto-generated from source code.  
> To update, run: \`npm run docs:generate -- --tools\`

---

## Overview

MyloWare exposes 10+ MCP tools for memory, coordination, and execution.

**Tool Categories:**
- **Memory Tools** - Search and store memories
- **Trace Tools** - Create and coordinate production runs
- **Context Tools** - Load persona and project configuration
- **Session Tools** - Manage conversation state
- **Job Tools** - Track async video/edit jobs

---

## Memory Tools

### memory_search

Search memories using hybrid vector + keyword retrieval.

**Parameters:**
- \`query\` (string, required) - Search query
- \`traceId\` (string, recommended) - Filter to specific trace
- \`project\` (string, recommended) - Filter to specific project
- \`persona\` (string, optional) - Filter to specific persona
- \`memoryTypes\` (array, optional) - Filter by type: episodic, semantic, procedural
- \`limit\` (number, optional) - Max results (default: 10)
- \`minSimilarity\` (number, optional) - Similarity threshold 0-1 (default: 0.7)
- \`temporalBoost\` (boolean, optional) - Boost recent memories (default: false)
- \`expandGraph\` (boolean, optional) - Follow memory links (default: false)

**Returns:**
\`\`\`typescript
{
  memories: Array<{
    id: string;
    content: string;
    summary?: string;
    memoryType: 'episodic' | 'semantic' | 'procedural';
    persona: string[];
    project: string[];
    tags: string[];
    relevanceScore: number;
    createdAt: string;
  }>;
}
\`\`\`

**Example:**
\`\`\`json
{
  "query": "Iggy's modifiers for trace-001",
  "traceId": "trace-001",
  "project": "aismr",
  "memoryTypes": ["episodic"],
  "limit": 12
}
\`\`\`

---

### memory_store

Store a new memory with automatic embedding and linking.

**Parameters:**
- \`content\` (string, required) - Single-line memory content (no newlines)
- \`memoryType\` (string, required) - episodic | semantic | procedural
- \`persona\` (array, optional) - Personas associated (e.g., ["iggy"])
- \`project\` (array, optional) - Projects associated (e.g., ["aismr"])
- \`tags\` (array, optional) - Descriptive tags (e.g., ["ideas", "approved"])
- \`metadata\` (object, optional) - **Must include \`traceId\` for coordination**
- \`relatedTo\` (array, optional) - UUIDs of related memories

**Returns:**
\`\`\`typescript
{
  id: string;
  content: string;
  memoryType: string;
  createdAt: string;
}
\`\`\`

**Example:**
\`\`\`json
{
  "content": "Generated 12 AISMR modifiers: Void, Liquid, Crystal...",
  "memoryType": "episodic",
  "persona": ["iggy"],
  "project": ["aismr"],
  "tags": ["ideas", "generated"],
  "metadata": {
    "traceId": "trace-001",
    "object": "candles"
  }
}
\`\`\`

---

### memory_evolve

Update an existing memory's tags, links, or summary.

**Parameters:**
- \`memoryId\` (string, required) - UUID of memory to update
- \`tags\` (array, optional) - New tags (replaces existing)
- \`relatedTo\` (array, optional) - New related memory UUIDs
- \`summary\` (string, optional) - New summary

**Returns:**
\`\`\`typescript
{
  id: string;
  updatedAt: string;
}
\`\`\`

---

## Trace Tools

### trace_create

Create a new execution trace for a production run.

**Parameters:**
- \`projectId\` (string, required) - Project UUID or slug
- \`sessionId\` (string, optional) - Session reference (e.g., "telegram:123")
- \`metadata\` (object, optional) - Additional context

**Returns:**
\`\`\`typescript
{
  traceId: string;
  projectId: string;
  currentOwner: string;
  status: 'active';
  createdAt: string;
}
\`\`\`

**Example:**
\`\`\`json
{
  "projectId": "550e8400-e29b-41d4-a716-446655440000",
  "sessionId": "telegram:123",
  "metadata": {
    "source": "telegram",
    "userMessage": "Make AISMR candles video"
  }
}
\`\`\`

---

### trace_update

Update trace metadata or instructions (Casey only).

**Parameters:**
- \`traceId\` (string, required) - Trace identifier
- \`projectId\` (string, optional) - Update project
- \`instructions\` (string, optional) - Update instructions
- \`metadata\` (object, optional) - Update metadata

**Returns:**
\`\`\`typescript
{
  traceId: string;
  updatedAt: string;
}
\`\`\`

---

### handoff_to_agent

Hand off work to another agent via webhook.

**Parameters:**
- \`traceId\` (string, required) - Trace identifier
- \`toAgent\` (string, required) - Target persona (or "complete" / "error")
- \`instructions\` (string, required) - Natural language instructions (2-4 sentences)
- \`metadata\` (object, optional) - Additional context

**Special targets:**
- \`toAgent: 'complete'\` - Marks trace completed, sends user notification
- \`toAgent: 'error'\` - Marks trace failed, logs error

**Returns:**
\`\`\`typescript
{
  webhookUrl: string;
  executionId: string;
  status: string;
  toAgent: string;
}
\`\`\`

**Example:**
\`\`\`json
{
  "traceId": "trace-001",
  "toAgent": "riley",
  "instructions": "Write 12 screenplays for the modifiers I generated. Each should be 8.0s, AISMR format. Find modifiers in memory tagged with trace-001 and persona iggy."
}
\`\`\`

---

## Context Tools

### context_get_persona

Load persona configuration and guardrails.

**Parameters:**
- \`name\` (string, required) - Persona name (casey, iggy, riley, etc.)

**Returns:**
\`\`\`typescript
{
  name: string;
  title: string;
  systemPrompt: string;
  allowedTools: string[];
  guardrails: object;
}
\`\`\`

---

### context_get_project

Load project configuration and specs.

**Parameters:**
- \`projectId\` (string, required) - Project UUID or slug

**Returns:**
\`\`\`typescript
{
  id: string;
  slug: string;
  name: string;
  workflow: string[];
  optionalSteps: string[];
  specs: object;
  guardrails: object;
}
\`\`\`

---

## Session Tools

### session_get_context

Get or create a session with working memory.

**Parameters:**
- \`sessionId\` (string, required) - Session identifier
- \`persona\` (string, optional) - Active persona
- \`project\` (string, optional) - Active project

**Returns:**
\`\`\`typescript
{
  sessionId: string;
  userId: string;
  persona: string;
  project: string;
  context: object;
  conversationHistory: array;
}
\`\`\`

---

### session_update_context

Update session working memory.

**Parameters:**
- \`sessionId\` (string, required) - Session identifier
- \`context\` (object, required) - Working memory to store

**Returns:**
\`\`\`typescript
{
  sessionId: string;
  updatedAt: string;
}
\`\`\`

---

## Job Tools

### job_upsert

Track async video/edit jobs (Veo/Alex only).

**Parameters:**
- \`traceId\` (string, required) - Associated trace
- \`kind\` (string, required) - "video" | "edit"
- \`provider\` (string, required) - Provider name (runway, shotstack, etc.)
- \`taskId\` (string, required) - External job ID
- \`status\` (string, required) - queued | running | succeeded | failed
- \`url\` (string, optional) - Result URL (when succeeded)
- \`error\` (string, optional) - Error message (when failed)

**Returns:**
\`\`\`typescript
{
  jobId: string;
  status: string;
}
\`\`\`

---

### jobs_summary

Check job completion status for a trace.

**Parameters:**
- \`traceId\` (string, required) - Associated trace

**Returns:**
\`\`\`typescript
{
  pending: number;
  running: number;
  succeeded: number;
  failed: number;
  total: number;
}
\`\`\`

**Usage:** Veo/Alex wait until \`pending === 0\` before handing off.

---

## Tool Access by Persona

| Persona | Tools |
|---------|-------|
| Casey | trace_update, memory_search, memory_store, handoff_to_agent, context_get_persona, context_get_project |
| Iggy | memory_search, memory_store, handoff_to_agent |
| Riley | memory_search, memory_store, handoff_to_agent |
| Veo | memory_search, memory_store, job_upsert, jobs_summary, handoff_to_agent |
| Alex | memory_search, memory_store, job_upsert, jobs_summary, handoff_to_agent |
| Quinn | memory_search, memory_store, handoff_to_agent |

---

## Common Patterns

### Load upstream work
\`\`\`json
{
  "name": "memory_search",
  "arguments": {
    "query": "Riley's screenplays for trace-001",
    "traceId": "trace-001",
    "persona": "riley",
    "memoryTypes": ["episodic"],
    "limit": 12
  }
}
\`\`\`

### Store outputs
\`\`\`json
{
  "name": "memory_store",
  "arguments": {
    "content": "Generated 12 videos for AISMR candles",
    "memoryType": "episodic",
    "persona": ["veo"],
    "project": ["aismr"],
    "tags": ["video", "generated"],
    "metadata": {
      "traceId": "trace-001",
      "videoUrls": ["https://...", "https://..."]
    }
  }
}
\`\`\`

### Hand off to next agent
\`\`\`json
{
  "name": "handoff_to_agent",
  "arguments": {
    "traceId": "trace-001",
    "toAgent": "alex",
    "instructions": "Stitch 12 videos into compilation. AISMR style: sequential with title cards. ~110s total. Find video URLs in memory trace-001 veo."
  }
}
\`\`\`

### Signal completion
\`\`\`json
{
  "name": "handoff_to_agent",
  "arguments": {
    "traceId": "trace-001",
    "toAgent": "complete",
    "instructions": "Published AISMR candles compilation to TikTok successfully. URL: https://tiktok.com/..."
  }
}
\`\`\`

---

## Further Reading

- [Prompt Notes](prompt-notes.md) - Agent prompt patterns
- [Trace State Machine](../02-architecture/trace-state-machine.md) - Coordination details
- [System Overview](../02-architecture/system-overview.md) - Architecture
- Source code: \`src/mcp/tools.ts\`
`;

  const outputPath = join(DOCS_DIR, 'mcp-tools.md');
  writeFileSync(outputPath, content, 'utf-8');
  console.log(`✓ Generated: ${outputPath}`);
}

/**
 * Generate schema documentation from src/db/schema.ts
 */
function generateSchemaDocs() {
  console.log('Generating schema documentation...');
  
  const content = `# Database Schema Reference

**Auto-generated from \`src/db/schema.ts\`**  
**Last updated:** ${new Date().toISOString().split('T')[0]}

> ⚠️ **Do not edit this file manually.** It is auto-generated from source code.  
> To update, run: \`npm run docs:generate -- --schema\`

---

## Overview

MyloWare uses PostgreSQL 15+ with the pgvector extension.

**Key tables:**
- \`execution_traces\` - Trace state machine
- \`memories\` - Vector + relational memory storage
- \`personas\` - AI agent configuration
- \`projects\` - Production type configuration
- \`agent_webhooks\` - Webhook registration
- \`sessions\` - Conversation state
- \`video_generation_jobs\` - Async video job tracking
- \`edit_jobs\` - Async edit job tracking

For architectural overview, see [Data Model](../02-architecture/data-model.md).

---

## Schema Generation

To inspect the current schema:

\`\`\`bash
# Generate schema SQL
npx drizzle-kit generate

# Push to database
npx drizzle-kit push

# View schema
psql $DATABASE_URL -c "\\d+ execution_traces"
\`\`\`

---

## Table Definitions

### execution_traces

Trace state machine for agent coordination.

\`\`\`sql
CREATE TABLE execution_traces (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  trace_id TEXT UNIQUE NOT NULL,
  project_id TEXT NOT NULL,
  session_id TEXT,
  current_owner TEXT NOT NULL DEFAULT 'casey',
  previous_owner TEXT,
  workflow_step INTEGER NOT NULL DEFAULT 0,
  instructions TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMP DEFAULT NOW(),
  completed_at TIMESTAMP,
  metadata JSONB DEFAULT '{}'
);

CREATE INDEX idx_execution_traces_trace_id ON execution_traces(trace_id);
CREATE INDEX idx_execution_traces_status ON execution_traces(status);
CREATE INDEX idx_execution_traces_current_owner ON execution_traces(current_owner);
\`\`\`

---

### memories

Vector + relational memory storage.

\`\`\`sql
CREATE TABLE memories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  content TEXT NOT NULL,
  summary TEXT,
  embedding VECTOR(1536) NOT NULL,
  memory_type TEXT NOT NULL,
  persona TEXT[] DEFAULT '{}',
  project TEXT[] DEFAULT '{}',
  tags TEXT[] DEFAULT '{}',
  related_to UUID[] DEFAULT '{}',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  last_accessed_at TIMESTAMP,
  access_count INTEGER DEFAULT 0,
  metadata JSONB DEFAULT '{}'
);

-- Vector similarity index (HNSW)
CREATE INDEX idx_memories_embedding ON memories 
USING hnsw (embedding vector_cosine_ops);

-- Array containment indices (GIN)
CREATE INDEX idx_memories_persona ON memories USING gin(persona);
CREATE INDEX idx_memories_project ON memories USING gin(project);
CREATE INDEX idx_memories_tags ON memories USING gin(tags);

-- Full-text search index
CREATE INDEX idx_memories_content_fts ON memories 
USING gin(to_tsvector('english', content));

-- Metadata index
CREATE INDEX idx_memories_metadata ON memories USING gin(metadata);
\`\`\`

---

### personas

AI agent configuration.

\`\`\`sql
CREATE TABLE personas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  system_prompt TEXT NOT NULL,
  allowed_tools TEXT[] DEFAULT '{}',
  guardrails JSONB DEFAULT '{}',
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_personas_name ON personas(name);
\`\`\`

---

### projects

Production type configuration.

\`\`\`sql
CREATE TABLE projects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  workflow TEXT[] NOT NULL DEFAULT '{}',
  optional_steps TEXT[] DEFAULT '{}',
  specs JSONB DEFAULT '{}',
  guardrails JSONB DEFAULT '{}',
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_projects_slug ON projects(slug);
\`\`\`

---

### agent_webhooks

Webhook registration for agent handoffs.

\`\`\`sql
CREATE TABLE agent_webhooks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_name TEXT UNIQUE NOT NULL,
  webhook_path TEXT NOT NULL,
  method TEXT NOT NULL DEFAULT 'POST',
  auth_type TEXT NOT NULL DEFAULT 'none',
  auth_config JSONB DEFAULT '{}',
  description TEXT,
  is_active BOOLEAN DEFAULT true,
  timeout_ms INTEGER,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_agent_webhooks_agent_name ON agent_webhooks(agent_name);
CREATE INDEX idx_agent_webhooks_is_active ON agent_webhooks(is_active);
\`\`\`

---

### sessions

Conversation state management.

\`\`\`sql
CREATE TABLE sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id TEXT UNIQUE NOT NULL,
  user_id TEXT NOT NULL,
  persona TEXT,
  project TEXT,
  context JSONB DEFAULT '{}',
  conversation_history JSONB[] DEFAULT '{}',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_sessions_session_id ON sessions(session_id);
CREATE INDEX idx_sessions_user_id ON sessions(user_id);
\`\`\`

---

### video_generation_jobs

Async video generation job tracking.

\`\`\`sql
CREATE TABLE video_generation_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id TEXT UNIQUE NOT NULL,
  trace_id TEXT NOT NULL,
  screenplay_id UUID,
  provider TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued',
  video_url TEXT,
  error TEXT,
  started_at TIMESTAMP,
  completed_at TIMESTAMP,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_video_generation_jobs_trace_id ON video_generation_jobs(trace_id);
CREATE INDEX idx_video_generation_jobs_status ON video_generation_jobs(status);
\`\`\`

---

### edit_jobs

Async video editing job tracking.

\`\`\`sql
CREATE TABLE edit_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id TEXT UNIQUE NOT NULL,
  trace_id TEXT NOT NULL,
  input_video_urls TEXT[] NOT NULL,
  provider TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued',
  output_url TEXT,
  error TEXT,
  started_at TIMESTAMP,
  completed_at TIMESTAMP,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_edit_jobs_trace_id ON edit_jobs(trace_id);
CREATE INDEX idx_edit_jobs_status ON edit_jobs(status);
\`\`\`

---

## Enums

### memory_type
- \`episodic\` - Events, interactions, history
- \`semantic\` - Facts, rules, specifications
- \`procedural\` - Workflows, processes, how-tos

### trace_status
- \`active\` - Production run in progress
- \`completed\` - Successfully finished
- \`failed\` - Encountered blocking error

### job_status
- \`queued\` - Waiting to start
- \`running\` - In progress
- \`succeeded\` - Completed successfully
- \`failed\` - Encountered error
- \`canceled\` - Manually canceled

---

## Relationships

\`\`\`
execution_traces
  ├─► project_id → projects.id
  └─► session_id → sessions.session_id

memories
  ├─► persona[] → personas.name
  ├─► project[] → projects.slug
  ├─► related_to[] → memories.id
  └─► metadata.traceId → execution_traces.trace_id

agent_webhooks
  └─► agent_name → personas.name

video_generation_jobs
  └─► trace_id → execution_traces.trace_id

edit_jobs
  └─► trace_id → execution_traces.trace_id
\`\`\`

---

## Migrations

MyloWare uses a **single squashed migration** approach:
- All schema in \`drizzle/0000_initial_schema.sql\`
- No incremental migrations
- Schema changes require updating the squashed file

**Commands:**
\`\`\`bash
# Reset local database
npm run db:reset -- --force

# Bootstrap (reset + migrate + seed)
npm run db:bootstrap -- --seed

# Migrate production
npm run db:migrate
\`\`\`

---

## Further Reading

- [Data Model](../02-architecture/data-model.md) - Architectural overview
- [Trace State Machine](../02-architecture/trace-state-machine.md) - Coordination details
- Source code: \`src/db/schema.ts\`
`;

  const outputPath = join(DOCS_DIR, 'schema.md');
  writeFileSync(outputPath, content, 'utf-8');
  console.log(`✓ Generated: ${outputPath}`);
}

// Main
try {
  if (generateTools) {
    generateToolsDocs();
  }
  
  if (generateSchema) {
    generateSchemaDocs();
  }
  
  console.log('\n✓ Documentation generation complete');
  process.exit(0);
} catch (error) {
  console.error('✗ Documentation generation failed:', error);
  process.exit(1);
}


